2021-08-19 15:26:27,089 [http-nio-8081-exec-5] INFO  org.anatkor.servlets.BikesListServlet- Bike servlet called
2021-08-19 15:26:27,099 [http-nio-8081-exec-5] DEBUG org.anatkor.dao.Utils- connection try
2021-08-19 15:26:27,104 [http-nio-8081-exec-5] DEBUG org.anatkor.dao.Utils- connection created succesfully
2021-08-19 16:03:52,984 [http-nio-8081-exec-12] DEBUG org.anatkor.dao.Utils- connection try
2021-08-19 16:03:52,998 [http-nio-8081-exec-12] DEBUG org.anatkor.dao.Utils- connection created succesfully
2021-08-19 16:03:53,124 [http-nio-8081-exec-12] INFO  org.anatkor.dao.UserDao- User with id =null is added
2021-08-19 16:03:53,126 [http-nio-8081-exec-12] INFO  org.anatkor.dao.UserDao- User with id 1 with role  is added
2021-08-19 16:08:23,242 [http-nio-8081-exec-21] DEBUG org.anatkor.dao.Utils- connection try
2021-08-19 16:08:23,243 [http-nio-8081-exec-21] DEBUG org.anatkor.dao.Utils- connection created succesfully
2021-08-19 16:08:23,295 [http-nio-8081-exec-21] DEBUG org.anatkor.dao.UserDao- SQLException during Add user with id null processing class org.anatkor.dao.Utils. ERROR: duplicate key value violates unique constraint "usr_email_key"
  Detail: Key (email)=(email@c.com) already exists.
2021-08-19 16:08:58,740 [http-nio-8081-exec-14] DEBUG org.anatkor.dao.Utils- connection try
2021-08-19 16:08:58,741 [http-nio-8081-exec-14] DEBUG org.anatkor.dao.Utils- connection created succesfully
2021-08-19 16:08:58,788 [http-nio-8081-exec-14] DEBUG org.anatkor.dao.UserDao- SQLException during Add user with id null processing class org.anatkor.dao.Utils. ERROR: duplicate key value violates unique constraint "usr_email_key"
  Detail: Key (email)=(email@c.com) already exists.
2021-08-19 16:15:24,132 [http-nio-8081-exec-26] DEBUG org.anatkor.dao.Utils- connection try
2021-08-19 16:15:24,133 [http-nio-8081-exec-26] DEBUG org.anatkor.dao.Utils- connection created succesfully
2021-08-19 16:15:24,180 [http-nio-8081-exec-26] DEBUG org.anatkor.dao.UserDao- SQLException during Add user with id null processing class org.anatkor.dao.Utils. ERROR: duplicate key value violates unique constraint "usr_email_key"
  Detail: Key (email)=(email@c.com) already exists.
2021-08-19 16:17:46,400 [http-nio-8081-exec-21] DEBUG org.anatkor.dao.Utils- connection try
2021-08-19 16:17:46,401 [http-nio-8081-exec-21] DEBUG org.anatkor.dao.Utils- connection created succesfully
2021-08-19 16:17:46,448 [http-nio-8081-exec-21] DEBUG org.anatkor.dao.UserDao- SQLException during Add user with id null processing class org.anatkor.dao.Utils. ERROR: duplicate key value violates unique constraint "usr_email_key"
  Detail: Key (email)=(email@c.com) already exists.
2021-08-19 16:18:46,603 [http-nio-8081-exec-25] DEBUG org.anatkor.dao.Utils- connection try
2021-08-19 16:18:46,617 [http-nio-8081-exec-25] DEBUG org.anatkor.dao.Utils- connection created succesfully
2021-08-19 16:18:46,843 [http-nio-8081-exec-25] DEBUG org.anatkor.dao.UserDao- SQLException during Add user with id null processing class org.anatkor.dao.Utils. ERROR: duplicate key value violates unique constraint "usr_email_key"
  Detail: Key (email)=(email@c.com) already exists.
2021-08-19 16:19:39,523 [http-nio-8081-exec-23] DEBUG org.anatkor.dao.Utils- connection try
2021-08-19 16:19:39,536 [http-nio-8081-exec-23] DEBUG org.anatkor.dao.Utils- connection created succesfully
2021-08-19 16:19:39,812 [http-nio-8081-exec-23] DEBUG org.anatkor.dao.UserDao- SQLException during Add user with id null processing class org.anatkor.dao.Utils. ERROR: duplicate key value violates unique constraint "usr_email_key"
  Detail: Key (email)=(email@c.com) already exists.
2021-08-19 16:27:03,869 [http-nio-8081-exec-44] DEBUG org.anatkor.dao.Utils- connection try
2021-08-19 16:27:03,881 [http-nio-8081-exec-44] DEBUG org.anatkor.dao.Utils- connection created succesfully
2021-08-19 16:27:04,003 [http-nio-8081-exec-44] INFO  org.anatkor.dao.UserDao- User with phone =381111111111 is added
2021-08-19 16:27:04,004 [http-nio-8081-exec-44] INFO  org.anatkor.dao.UserDao- User with id 8 with role  is added
2021-08-19 16:27:04,008 [http-nio-8081-exec-40] DEBUG org.anatkor.servlets.LoginServlet- User servlet called
2021-08-19 16:32:41,178 [http-nio-8081-exec-46] INFO  org.anatkor.dao.UserDao- User with phone =382222222222 is added
2021-08-19 16:32:41,186 [http-nio-8081-exec-46] INFO  org.anatkor.dao.UserDao- User with id 9 with role  is added
2021-08-19 16:32:41,192 [http-nio-8081-exec-47] DEBUG org.anatkor.servlets.LoginServlet- User servlet called
2021-08-19 16:37:54,437 [http-nio-8081-exec-56] DEBUG org.anatkor.dao.UserDao- SQLException during Add user with id null processing class org.anatkor.dao.Utils. ERROR: duplicate key value violates unique constraint "usr_email_key"
  Detail: Key (email)=(email@c.com) already exists.
2021-08-19 16:39:54,976 [http-nio-8081-exec-59] DEBUG org.anatkor.dao.UserDao- SQLException during Add user with id null processing class org.anatkor.dao.Utils. ERROR: duplicate key value violates unique constraint "usr_email_key"
  Detail: Key (email)=(email@c.com) already exists.
2021-08-19 16:40:04,803 [http-nio-8081-exec-60] DEBUG org.anatkor.dao.UserDao- SQLException during Add user with id null processing class org.anatkor.dao.Utils. ERROR: duplicate key value violates unique constraint "usr_phone_number_key"
  Detail: Key (phone_number)=(381111111111) already exists.
2021-08-19 16:41:46,982 [http-nio-8081-exec-57] INFO  org.anatkor.dao.UserDao- User with phone =383333333333 is added
2021-08-19 16:41:46,983 [http-nio-8081-exec-57] INFO  org.anatkor.dao.UserDao- User with id 13 with role  is added
2021-08-19 16:41:46,987 [http-nio-8081-exec-58] DEBUG org.anatkor.servlets.LoginServlet- User servlet called
2021-08-19 16:42:38,867 [http-nio-8081-exec-57] INFO  org.anatkor.dao.UserDao- User with phone =384444444444 is added
2021-08-19 16:42:38,875 [http-nio-8081-exec-57] INFO  org.anatkor.dao.UserDao- User with id 14 with role  is added
2021-08-19 16:42:38,880 [http-nio-8081-exec-64] DEBUG org.anatkor.servlets.LoginServlet- User servlet called
2021-08-19 16:50:52,169 [http-nio-8081-exec-71] DEBUG org.anatkor.dao.UserDao- SQLException during Add user with id null processing class org.anatkor.dao.Utils. ERROR: duplicate key value violates unique constraint "usr_email_key"
  Detail: Key (email)=(email@c.com) already exists.
2021-08-19 16:51:13,336 [http-nio-8081-exec-67] DEBUG org.anatkor.dao.UserDao- SQLException during Add user with id null processing class org.anatkor.dao.Utils. ERROR: duplicate key value violates unique constraint "usr_phone_number_key"
  Detail: Key (phone_number)=(381111111111) already exists.
2021-08-19 16:52:33,410 [http-nio-8081-exec-80] DEBUG org.anatkor.dao.UserDao- SQLException during Add user with id null processing class org.anatkor.dao.Utils. ERROR: duplicate key value violates unique constraint "usr_email_key"
  Detail: Key (email)=(email@c.com) already exists.
2021-08-19 16:52:45,677 [http-nio-8081-exec-77] DEBUG org.anatkor.dao.UserDao- SQLException during Add user with id null processing class org.anatkor.dao.Utils. ERROR: duplicate key value violates unique constraint "usr_email_key"
  Detail: Key (email)=(email@c.com) already exists.
2021-08-19 17:13:50,159 [http-nio-8081-exec-83] DEBUG org.anatkor.dao.UserDao- SQLException during Add user with phone 382222222222 processing class org.anatkor.dao.Utils. ERROR: duplicate key value violates unique constraint "usr_email_key"
  Detail: Key (email)=(email@c.com) already exists.
2021-08-19 17:14:05,403 [http-nio-8081-exec-87] DEBUG org.anatkor.dao.UserDao- SQLException during Add user with phone 382222222222 processing class org.anatkor.dao.Utils. ERROR: duplicate key value violates unique constraint "usr_email_key"
  Detail: Key (email)=(email@c.com) already exists.
2021-08-19 17:14:34,132 [http-nio-8081-exec-85] DEBUG org.anatkor.dao.UserDao- SQLException during Add user with phone 381111111111 processing class org.anatkor.dao.Utils. ERROR: duplicate key value violates unique constraint "usr_email_key"
  Detail: Key (email)=(email@c.com) already exists.
2021-08-19 17:14:43,282 [http-nio-8081-exec-91] DEBUG org.anatkor.dao.UserDao- SQLException during Add user with phone 381111111111 processing class org.anatkor.dao.Utils. ERROR: duplicate key value violates unique constraint "usr_email_key"
  Detail: Key (email)=(email@c.com) already exists.
2021-08-19 17:15:15,732 [http-nio-8081-exec-93] DEBUG org.anatkor.dao.UserDao- SQLException during Add user with phone 381111111111 processing class org.anatkor.dao.Utils. ERROR: duplicate key value violates unique constraint "usr_email_key"
  Detail: Key (email)=(email@c.com) already exists.
2021-08-19 17:15:39,681 [http-nio-8081-exec-92] DEBUG org.anatkor.dao.UserDao- SQLException during Add user with phone 382222222222 processing class org.anatkor.dao.Utils. ERROR: duplicate key value violates unique constraint "usr_email_key"
  Detail: Key (email)=(email@c.com) already exists.
2021-08-19 17:17:22,450 [http-nio-8081-exec-91] DEBUG org.anatkor.dao.UserDao- SQLException during Add user with phone 382222222222 processing class org.anatkor.dao.Utils. ERROR: duplicate key value violates unique constraint "usr_email_key"
  Detail: Key (email)=(email@c.com) already exists.
2021-08-19 17:18:29,440 [http-nio-8081-exec-93] DEBUG org.anatkor.dao.UserDao- SQLException during Add user with phone 382222222222 processing class org.anatkor.dao.Utils. ERROR: duplicate key value violates unique constraint "usr_email_key"
  Detail: Key (email)=(email@c.com) already exists.
2021-08-19 17:18:58,497 [http-nio-8081-exec-92] DEBUG org.anatkor.dao.UserDao- SQLException during Add user with phone 382222222222 processing class org.anatkor.dao.Utils. ERROR: duplicate key value violates unique constraint "usr_phone_number_key"
  Detail: Key (phone_number)=(382222222222) already exists.
2021-08-19 17:19:37,944 [http-nio-8081-exec-91] DEBUG org.anatkor.dao.UserDao- SQLException during Add user with phone 382222222222 processing class org.anatkor.dao.Utils. ERROR: duplicate key value violates unique constraint "usr_email_key"
  Detail: Key (email)=(email@c.com) already exists.
2021-08-19 17:19:52,327 [http-nio-8081-exec-94] DEBUG org.anatkor.dao.UserDao- SQLException during Add user with phone 381111111111 processing class org.anatkor.dao.Utils. ERROR: duplicate key value violates unique constraint "usr_phone_number_key"
  Detail: Key (phone_number)=(381111111111) already exists.
